gg:
  jte:
    development-mode: true
spring:
  application:
    name: crac
  main:
    cloud-platform: none
    
management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health

logging:
  level:
    root: info
    com.braintrustappliedresearch: debug

SUPER_SECRET: ${ENV_SUPER_SECRET}
